language: android
jdk: openjdk8
sudo: false

env:
  global:

notifications:
  email:
    - baneeishaque@gmail.com

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

before_install:
  # - echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
  # - echo "org.gradle.configureondemand=true" >> ~/.gradle/gradle.properties
  # - echo "org.gradle.jvmargs=-Xmx8192m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> ~/.gradle/gradle.properties

  - chmod +x gradlew

script: ./gradlew build

after_success:
  - ls -R "${TRAVIS_BUILD_DIR}/${DIR}app/build/outputs/"